-- Migration: Create organization_staff table for assigning multiple staff to an organization

CREATE TABLE IF NOT EXISTS public.organization_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE CASCADE,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Ensure an employee is not assigned to the same organization more than once
    UNIQUE(organization_id, employee_id)
);

-- Enable RLS (Row Level Security) if needed, otherwise allow all for now (matching existing tables)
ALTER TABLE public.organization_staff ENABLE ROW LEVEL SECURITY;

-- Optional: Create basic policies so the API can read/write
CREATE POLICY "Allow all operations for authenticated users" 
ON public.organization_staff
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);
