-- Migration 01: Branch Management & Branch Inventory Schema

-- 1. Create Branches table
CREATE TABLE IF NOT EXISTS public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    tier TEXT NOT NULL DEFAULT 'Branch', -- Corporate, Branch, Factory
    address TEXT,
    contact_number TEXT,
    email TEXT,
    operational_settings JSONB DEFAULT '{}'::jsonb,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Seed default Corporate, Factory, and Branch entries if empty
INSERT INTO public.branches (code, name, tier, address)
SELECT 'CORP-01', 'Headquarters Corporate', 'Corporate', 'Main Corporate HQ'
WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE code = 'CORP-01');

INSERT INTO public.branches (code, name, tier, address)
SELECT 'FACT-01', 'Central Factory Unit', 'Factory', 'Industrial Zone Factory 1'
WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE code = 'FACT-01');

INSERT INTO public.branches (code, name, tier, address)
SELECT 'BR-01', 'Majestic Center Branch', 'Branch', 'Majestic Center'
WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE code = 'BR-01');

-- 2. Add branch_id to core operational tables
ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.stock_movements ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.quotations ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);

-- 3. Create purchase_entry_batches for Vendor Bill Number + Lump Number tracking
CREATE TABLE IF NOT EXISTS public.purchase_entry_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no TEXT UNIQUE NOT NULL, -- Auto: BILL_NO + '-' + LUMP_NO
    vendor_bill_no TEXT NOT NULL,
    lump_no TEXT NOT NULL,
    item_type TEXT NOT NULL, -- fabric, button, thread, readymade
    item_id BIGINT,
    branch_id BIGINT REFERENCES public.branches(id),
    quantity NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    unit TEXT DEFAULT 'meters',
    received_date DATE DEFAULT CURRENT_DATE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS policies
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_entry_batches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for authenticated users on branches" ON public.branches FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for authenticated users on purchase_entry_batches" ON public.purchase_entry_batches FOR ALL TO authenticated USING (true) WITH CHECK (true);
