-- Migration 02: Factory & Production Operations (Job Cards, Sub-Job Cards, Fabric Consumption)

-- 1. Create Job Cards table
CREATE TABLE IF NOT EXISTS public.job_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_card_no TEXT UNIQUE NOT NULL, -- e.g. JC-26/09-0001
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    quotation_id BIGINT REFERENCES public.quotations(id),
    item_id BIGINT, -- product / quotation_item reference
    design_number TEXT,
    item_name TEXT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    size_breakdown JSONB DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'Draft', -- Draft, Pending PO Handler, Accepted, Rejected, Hold, In Production, Completed
    po_handler_action TEXT DEFAULT 'Pending', -- Pending, Accept, Reject, Hold
    po_handler_reason TEXT,
    hold_reason TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Sub Job Cards table (Batch Breakdown by Production Coordinator)
CREATE TABLE IF NOT EXISTS public.sub_job_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_card_no TEXT UNIQUE NOT NULL, -- e.g. SJC-26/09-0001-A
    job_card_id BIGINT REFERENCES public.job_cards(id) ON DELETE CASCADE,
    batch_size INT NOT NULL DEFAULT 1,
    stage TEXT NOT NULL DEFAULT 'Cutting', -- Cutting, Stitching, Finishing, QC, Packing, Ready
    assigned_to TEXT,
    target_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Fabric Consumption Logs table
CREATE TABLE IF NOT EXISTS public.fabric_consumption_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_card_id BIGINT REFERENCES public.job_cards(id) ON DELETE CASCADE,
    sub_job_card_id BIGINT REFERENCES public.sub_job_cards(id) ON DELETE SET NULL,
    fabric_id BIGINT,
    fabric_name TEXT,
    required_meters NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    safety_margin_meters NUMERIC(10,2) NOT NULL DEFAULT 0.00, -- Automatically 10% safety margin (required * 0.10)
    issued_meters NUMERIC(10,2) NOT NULL DEFAULT 0.00, -- required + safety_margin
    consumed_meters NUMERIC(10,2) DEFAULT 0.00,
    returned_meters NUMERIC(10,2) DEFAULT 0.00,
    cut_piece_batch_no TEXT, -- Batch number assigned to returned cut pieces
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS policies
ALTER TABLE public.job_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sub_job_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fabric_consumption_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for authenticated users on job_cards" ON public.job_cards FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for authenticated users on sub_job_cards" ON public.sub_job_cards FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for authenticated users on fabric_consumption_logs" ON public.fabric_consumption_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
