-- Migration 03: Basic Invoicing & Delivery Challans

-- 1. Create Invoices table
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no TEXT UNIQUE NOT NULL, -- e.g. YY/MM/INV-0001
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    quotation_id BIGINT REFERENCES public.quotations(id) ON DELETE SET NULL,
    branch_id BIGINT REFERENCES public.branches(id),
    customer_name TEXT NOT NULL,
    customer_type TEXT DEFAULT 'Business', -- Business (Organisation), Individual
    is_tax_inclusive BOOLEAN DEFAULT true,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    paid_amount NUMERIC(12,2) DEFAULT 0.00,
    payment_status TEXT DEFAULT 'Unpaid', -- Unpaid, Partially Paid, Fully Paid
    notes TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Invoice Items table
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES public.invoices(id) ON DELETE CASCADE,
    item_description TEXT NOT NULL,
    design_number TEXT,
    barcode TEXT,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    tax_rate NUMERIC(5,2) DEFAULT 0.00,
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Delivery Challans table
CREATE TABLE IF NOT EXISTS public.delivery_challans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dc_no TEXT UNIQUE NOT NULL, -- e.g. YY/MM/DC-0001
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.branches(id),
    dispatch_date DATE DEFAULT CURRENT_DATE,
    vehicle_no TEXT,
    transporter_name TEXT,
    total_packages INT DEFAULT 1,
    notes TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS policies
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_challans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for authenticated users on invoices" ON public.invoices FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for authenticated users on invoice_items" ON public.invoice_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for authenticated users on delivery_challans" ON public.delivery_challans FOR ALL TO authenticated USING (true) WITH CHECK (true);
