-- Migration 04: Measurement Tokens (Unique ID: Organisation + SO + Token + Item) & Timeline Logs

-- 1. Create Measurement Tokens table
CREATE TABLE IF NOT EXISTS public.measurement_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_number TEXT NOT NULL,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    member_id BIGINT REFERENCES public.registry_members(id) ON DELETE SET NULL,
    student_name TEXT NOT NULL,
    class_name TEXT,
    section_name TEXT,
    item_name TEXT NOT NULL,
    alteration_details TEXT,
    -- Composite Unique ID: Organisation + Sales Order + Token Number + Item
    unique_composite_id TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Assigned', -- Assigned, Captured, In Production, Delivered
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Record Activity Logs table for Quotations, SOs, and Job Cards timeline
CREATE TABLE IF NOT EXISTS public.record_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL, -- Quotation, Order, JobCard, Invoice
    entity_id BIGINT NOT NULL,
    action TEXT NOT NULL, -- Created, Approved, Rejected, Locked, Converted, Updated, AttachmentAdded
    performed_by BIGINT,
    performed_by_name TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    attachments JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS policies
ALTER TABLE public.measurement_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.record_activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for authenticated users on measurement_tokens" ON public.measurement_tokens FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for authenticated users on record_activity_logs" ON public.record_activity_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
