-- ==============================================================================
-- FORMA APPARELS ERP - PHASE 1: PIECE-LEVEL CHILD JOB CARDS & DUAL BARCODING
-- Complies with PRD M9.3, M9.4, M9.5, M9.6, M11.1, M11.2
-- ==============================================================================

-- 1. Create child_job_cards Table
CREATE TABLE IF NOT EXISTS public.child_job_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_card_no TEXT UNIQUE NOT NULL,                       -- e.g. CJC-26/09-1001-001
    job_card_id BIGINT REFERENCES public.job_cards(id) ON DELETE CASCADE,
    sub_job_card_id BIGINT REFERENCES public.sub_job_cards(id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    barcode TEXT NOT NULL,                                    -- Unified barcode for all pcs of the same person in the job card (e.g. CJC-7548-001)
    item_type TEXT NOT NULL DEFAULT 'standard',              -- 'standard' | 'custom'
    size TEXT,                                                -- '38', '40', 'S', 'M', 'L', etc.
    member_id BIGINT REFERENCES public.registry_members(id) ON DELETE SET NULL,
    member_name TEXT,                                         -- 'Rahul', 'Anil', etc.
    admission_no TEXT,                                        -- '#EMP-201', '#STU-105'
    custom_measurements JSONB DEFAULT '{}',                   -- { chest: 38, waist: 32, length: 28, ... }
    sequence_no INT NOT NULL DEFAULT 1,                       -- 1, 2, 3...
    stage TEXT NOT NULL DEFAULT 'Cutting',                    -- Cutting, Stitching, Finishing, QC, Packing, Ready
    status TEXT NOT NULL DEFAULT 'In Production',              -- In Production, Completed, Rejected, Rework
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Performance indices
CREATE INDEX IF NOT EXISTS idx_cjc_job_card ON public.child_job_cards(job_card_id);
CREATE INDEX IF NOT EXISTS idx_cjc_sub_job_card ON public.child_job_cards(sub_job_card_id);
CREATE INDEX IF NOT EXISTS idx_cjc_barcode ON public.child_job_cards(barcode);
CREATE INDEX IF NOT EXISTS idx_cjc_order ON public.child_job_cards(order_id);

-- Enable RLS
ALTER TABLE public.child_job_cards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all operations for authenticated users on child_job_cards" ON public.child_job_cards;
CREATE POLICY "Allow all operations for authenticated users on child_job_cards" 
ON public.child_job_cards FOR ALL USING (true);

-- 2. Add multi-size distribution support to sub_job_cards
ALTER TABLE public.sub_job_cards 
ADD COLUMN IF NOT EXISTS size_distribution JSONB DEFAULT '{}';

-- 3. Also append to PENDING_RUN_IN_SUPABASE.sql and RUN_ALL_PHASE1_MIGRATIONS.sql for records
