-- Migration: Create public.leads table
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    industry_id BIGINT REFERENCES public.industries(id) ON DELETE SET NULL,
    address TEXT,
    assigned_staff_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'New',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Permissive policies for internal/API access
CREATE POLICY "Allow read for leads" ON public.leads FOR SELECT USING (true);
CREATE POLICY "Allow all for leads" ON public.leads FOR ALL USING (true);

-- Reload Supabase PostgREST schema cache
NOTIFY pgrst, 'reload schema';

