-- Migration: Create public.vendors table
CREATE TABLE IF NOT EXISTS public.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;

-- Permissive policies for internal/API access
DROP POLICY IF EXISTS "Public Read" ON public.vendors;
DROP POLICY IF EXISTS "Admin All" ON public.vendors;
CREATE POLICY "Public Read" ON public.vendors FOR SELECT USING (true);
CREATE POLICY "Admin All" ON public.vendors FOR ALL USING (true);

-- Reload Supabase PostgREST schema cache
NOTIFY pgrst, 'reload schema';
