-- ================================================================
-- PENDING DATABASE MIGRATIONS
-- Run these SQL statements in your Supabase SQL Editor
-- (Project Settings > SQL Editor or Table Editor > SQL)
-- ================================================================

-- 1. Add design_number column to products table
--    This enables auto-generated DN-XXXX design numbers
ALTER TABLE public.products 
  ADD COLUMN IF NOT EXISTS design_number TEXT UNIQUE DEFAULT NULL;

-- 2. Create company_settings table for address and bank details
CREATE TABLE IF NOT EXISTS public.company_settings (
    id INT PRIMARY KEY DEFAULT 1,
    company_name TEXT DEFAULT 'Forma Apparels',
    address TEXT DEFAULT '63/3608, CD Tower, Arayidathupalam, Kozhikode, Kerala - 673 004, India',
    phone TEXT DEFAULT '(+91) 7902 499 990 | 0495 2 922 992',
    email TEXT DEFAULT 'info@formaapparels.com',
    website TEXT DEFAULT 'www.formaapparels.com',
    bank_name TEXT DEFAULT 'HDFC BANK',
    account_no TEXT DEFAULT '50200076116064',
    branch_name TEXT DEFAULT 'MAJESTIC CENTER',
    ifsc_code TEXT DEFAULT 'HDFC0001255',
    upi_id TEXT DEFAULT '7902 499 991',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT one_row CHECK (id = 1)
);

INSERT INTO public.company_settings (id, company_name)
VALUES (1, 'Forma Apparels')
ON CONFLICT (id) DO NOTHING;

-- 3. Add pdf_html column to quotations table
ALTER TABLE public.quotations 
  ADD COLUMN IF NOT EXISTS pdf_html TEXT;

-- 4. Add quantity and low_stock_threshold to buttons and threads tables
ALTER TABLE public.buttons
  ADD COLUMN IF NOT EXISTS quantity NUMERIC(10, 2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS low_stock_threshold NUMERIC(10, 2) DEFAULT 10.00;

ALTER TABLE public.threads
  ADD COLUMN IF NOT EXISTS quantity NUMERIC(10, 2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS low_stock_threshold NUMERIC(10, 2) DEFAULT 10.00;

-- 5. Add main_fabric_id, button_id, and thread_id back to products table
ALTER TABLE public.products 
  ADD COLUMN IF NOT EXISTS main_fabric_id UUID REFERENCES public.fabrics(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS button_id UUID REFERENCES public.buttons(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS thread_id UUID REFERENCES public.threads(id) ON DELETE SET NULL;

-- 6. Create product_design_variants table
CREATE TABLE IF NOT EXISTS public.product_design_variants (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    design_number_id BIGINT REFERENCES public.design_numbers(id) ON DELETE CASCADE UNIQUE,
    button_id UUID REFERENCES public.buttons(id) ON DELETE SET NULL,
    thread_id UUID REFERENCES public.threads(id) ON DELETE SET NULL,
    button_count INTEGER DEFAULT 0,
    thread_count INTEGER DEFAULT 0,
    material_combination TEXT,
    variant_status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(product_id, button_id, thread_id)
);

ALTER TABLE public.product_design_variants ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read" ON public.product_design_variants;
DROP POLICY IF EXISTS "Admin All" ON public.product_design_variants;
CREATE POLICY "Public Read" ON public.product_design_variants FOR SELECT USING (true);
CREATE POLICY "Admin All" ON public.product_design_variants FOR ALL USING (true);

-- ================================================================
-- All other migrations should already be applied.
-- The above is the only pending migration.
-- ================================================================

-- 7. Add latest_sam, vendors, and images columns to fabrics table
ALTER TABLE public.fabrics
  ADD COLUMN IF NOT EXISTS latest_sam NUMERIC(10,2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS vendors JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;

-- 8. Add images and vendors columns to buttons table
ALTER TABLE public.buttons
  ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS vendors JSONB DEFAULT '[]'::jsonb;

-- 9. Add images and vendors columns to threads table
ALTER TABLE public.threads
  ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS vendors JSONB DEFAULT '[]'::jsonb;

-- 10. Create public.vendors table for unified vendor registry
CREATE TABLE IF NOT EXISTS public.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS and permissive defaults
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read" ON public.vendors;
DROP POLICY IF EXISTS "Admin All" ON public.vendors;
CREATE POLICY "Public Read" ON public.vendors FOR SELECT USING (true);
CREATE POLICY "Admin All" ON public.vendors FOR ALL USING (true);

-- Reload Supabase PostgREST schema cache
NOTIFY pgrst, 'reload schema';

-- 11. Create public.leads table
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    industry_id BIGINT REFERENCES public.industries(id) ON DELETE SET NULL,
    address TEXT,
    assigned_staff_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'New',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- In case the leads table was already created without lead_code and phone:
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS lead_code TEXT UNIQUE;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS phone TEXT;

-- Enable RLS and setup permissive policies
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read for leads" ON public.leads;
DROP POLICY IF EXISTS "Allow all for leads" ON public.leads;
CREATE POLICY "Allow read for leads" ON public.leads FOR SELECT USING (true);
CREATE POLICY "Allow all for leads" ON public.leads FOR ALL USING (true);

-- Reload Supabase PostgREST schema cache
NOTIFY pgrst, 'reload schema';

-- 12. Add customer_code, relationship_manager_id, and assigned_operator_id columns to organizations table
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS customer_code TEXT UNIQUE;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS relationship_manager_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS assigned_operator_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL;

-- Backfill codes for existing organizations
DO $$
DECLARE
    r RECORD;
    cnt INT := 1;
BEGIN
    FOR r IN SELECT id FROM public.organizations WHERE customer_code IS NULL ORDER BY created_at ASC, id ASC LOOP
        UPDATE public.organizations 
        SET customer_code = 'CN' || lpad(cnt::text, 3, '0') 
        WHERE id = r.id;
        cnt := cnt + 1;
    END LOOP;
END $$;

-- Reload Supabase PostgREST schema cache
NOTIFY pgrst, 'reload schema';

-- 13. Add garment_category to fabrics table
ALTER TABLE public.fabrics ADD COLUMN IF NOT EXISTS garment_category VARCHAR(50);

-- Reload Supabase PostgREST schema cache
NOTIFY pgrst, 'reload schema';

