-- ================================================================
-- PHASE 1 CONSOLIDATED DATABASE MIGRATION (SAFE & COMPLETE)
-- Run this complete script in Supabase SQL Editor:
-- (Supabase Dashboard > SQL Editor > New Query > Run)
-- ================================================================

-- 1. Create Branches table
CREATE TABLE IF NOT EXISTS public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    tier TEXT NOT NULL DEFAULT 'Branch', -- Corporate, Branch, Factory
    address TEXT,
    contact_number TEXT,
    email TEXT,
    operational_settings JSONB DEFAULT '{}'::jsonb,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Seed default Corporate, Factory, and Branch entries if empty
INSERT INTO public.branches (code, name, tier, address)
SELECT 'CORP-01', 'Headquarters Corporate', 'Corporate', 'Main Corporate HQ'
WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE code = 'CORP-01');

INSERT INTO public.branches (code, name, tier, address)
SELECT 'FACT-01', 'Central Factory Unit', 'Factory', 'Industrial Zone Factory 1'
WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE code = 'FACT-01');

INSERT INTO public.branches (code, name, tier, address)
SELECT 'BR-01', 'Majestic Center Branch', 'Branch', 'Majestic Center'
WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE code = 'BR-01');

-- 2. Safely add branch_id to existing operational tables if they exist
DO $$ 
BEGIN 
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'inventory_items') THEN
        ALTER TABLE public.inventory_items ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'stock_movements') THEN
        ALTER TABLE public.stock_movements ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'quotations') THEN
        ALTER TABLE public.quotations ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'orders') THEN
        ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'leads') THEN
        ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
    END IF;
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'organizations') THEN
        ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS branch_id BIGINT REFERENCES public.branches(id);
    END IF;
END $$;

-- 3. Create purchase_entry_batches
CREATE TABLE IF NOT EXISTS public.purchase_entry_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no TEXT UNIQUE NOT NULL,
    vendor_bill_no TEXT NOT NULL,
    lump_no TEXT NOT NULL,
    item_type TEXT NOT NULL,
    item_id BIGINT,
    branch_id BIGINT REFERENCES public.branches(id),
    quantity NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    unit TEXT DEFAULT 'meters',
    received_date DATE DEFAULT CURRENT_DATE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Job Cards table
CREATE TABLE IF NOT EXISTS public.job_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_card_no TEXT UNIQUE NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    quotation_id BIGINT REFERENCES public.quotations(id),
    item_id BIGINT,
    design_number TEXT,
    item_name TEXT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    size_breakdown JSONB DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'Draft',
    po_handler_action TEXT DEFAULT 'Pending',
    po_handler_reason TEXT,
    hold_reason TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create Sub Job Cards table
CREATE TABLE IF NOT EXISTS public.sub_job_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_card_no TEXT UNIQUE NOT NULL,
    job_card_id BIGINT REFERENCES public.job_cards(id) ON DELETE CASCADE,
    batch_size INT NOT NULL DEFAULT 1,
    stage TEXT NOT NULL DEFAULT 'Cutting',
    assigned_to TEXT,
    target_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create Fabric Consumption Logs table
CREATE TABLE IF NOT EXISTS public.fabric_consumption_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_card_id BIGINT REFERENCES public.job_cards(id) ON DELETE CASCADE,
    sub_job_card_id BIGINT REFERENCES public.sub_job_cards(id) ON DELETE SET NULL,
    fabric_id BIGINT,
    fabric_name TEXT,
    required_meters NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    safety_margin_meters NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    issued_meters NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    consumed_meters NUMERIC(10,2) DEFAULT 0.00,
    returned_meters NUMERIC(10,2) DEFAULT 0.00,
    cut_piece_batch_no TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Create Invoices table
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no TEXT UNIQUE NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    quotation_id BIGINT REFERENCES public.quotations(id) ON DELETE SET NULL,
    branch_id BIGINT REFERENCES public.branches(id),
    customer_name TEXT NOT NULL,
    customer_type TEXT DEFAULT 'Business',
    is_tax_inclusive BOOLEAN DEFAULT true,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    paid_amount NUMERIC(12,2) DEFAULT 0.00,
    payment_status TEXT DEFAULT 'Unpaid',
    notes TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Create Invoice Items table
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES public.invoices(id) ON DELETE CASCADE,
    item_description TEXT NOT NULL,
    design_number TEXT,
    barcode TEXT,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    tax_rate NUMERIC(5,2) DEFAULT 0.00,
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Create Delivery Challans table
CREATE TABLE IF NOT EXISTS public.delivery_challans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dc_no TEXT UNIQUE NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.branches(id),
    dispatch_date DATE DEFAULT CURRENT_DATE,
    vehicle_no TEXT,
    transporter_name TEXT,
    total_packages INT DEFAULT 1,
    notes TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. Create Measurement Tokens table
CREATE TABLE IF NOT EXISTS public.measurement_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_number TEXT NOT NULL,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    member_id BIGINT REFERENCES public.registry_members(id) ON DELETE SET NULL,
    student_name TEXT NOT NULL,
    class_name TEXT,
    section_name TEXT,
    item_name TEXT NOT NULL,
    alteration_details TEXT,
    unique_composite_id TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Assigned',
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. Create Record Activity Logs table
CREATE TABLE IF NOT EXISTS public.record_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    performed_by BIGINT,
    performed_by_name TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    attachments JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. Create Branch Users Credentials Table
CREATE TABLE IF NOT EXISTS public.branch_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_plain TEXT NOT NULL,
    role TEXT DEFAULT 'Branch Manager',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. Create Branch Isolated Inventory Table
CREATE TABLE IF NOT EXISTS public.branch_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL,
    item_name TEXT NOT NULL,
    item_code TEXT,
    quantity NUMERIC(12,2) DEFAULT 0.00,
    unit TEXT DEFAULT 'units',
    low_stock_threshold NUMERIC(12,2) DEFAULT 10.00,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 14. Create Inter-Branch Stock Transfers Table
CREATE TABLE IF NOT EXISTS public.inter_branch_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no TEXT UNIQUE NOT NULL,
    from_branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    to_branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL,
    item_name TEXT NOT NULL,
    quantity NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status TEXT DEFAULT 'Dispatched',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS & Policies
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_entry_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sub_job_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fabric_consumption_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_challans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.measurement_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.record_activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inter_branch_transfers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all operations for authenticated users on branches" ON public.branches;
CREATE POLICY "Allow all operations for authenticated users on branches" ON public.branches FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on purchase_entry_batches" ON public.purchase_entry_batches;
CREATE POLICY "Allow all operations for authenticated users on purchase_entry_batches" ON public.purchase_entry_batches FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on job_cards" ON public.job_cards;
CREATE POLICY "Allow all operations for authenticated users on job_cards" ON public.job_cards FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on sub_job_cards" ON public.sub_job_cards;
CREATE POLICY "Allow all operations for authenticated users on sub_job_cards" ON public.sub_job_cards FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on fabric_consumption_logs" ON public.fabric_consumption_logs;
CREATE POLICY "Allow all operations for authenticated users on fabric_consumption_logs" ON public.fabric_consumption_logs FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on invoices" ON public.invoices;
CREATE POLICY "Allow all operations for authenticated users on invoices" ON public.invoices FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on invoice_items" ON public.invoice_items;
CREATE POLICY "Allow all operations for authenticated users on invoice_items" ON public.invoice_items FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on delivery_challans" ON public.delivery_challans;
CREATE POLICY "Allow all operations for authenticated users on delivery_challans" ON public.delivery_challans FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on measurement_tokens" ON public.measurement_tokens;
CREATE POLICY "Allow all operations for authenticated users on measurement_tokens" ON public.measurement_tokens FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all operations for authenticated users on record_activity_logs" ON public.record_activity_logs;
CREATE POLICY "Allow all operations for authenticated users on record_activity_logs" ON public.record_activity_logs FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all for branch_users" ON public.branch_users;
CREATE POLICY "Allow all for branch_users" ON public.branch_users FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all for branch_inventory" ON public.branch_inventory;
CREATE POLICY "Allow all for branch_inventory" ON public.branch_inventory FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all for inter_branch_transfers" ON public.inter_branch_transfers;
CREATE POLICY "Allow all for inter_branch_transfers" ON public.inter_branch_transfers FOR ALL USING (true);

-- Reload PostgREST schema cache immediately
NOTIFY pgrst, 'reload schema';
